language: java
jdk: oraclejdk7
script: mvn install -Pwhitebox -Pwildfly-managed -Pjacoco -Pcoveralls
deploy:
  provider: openshift
  user: rmpestano@gmail.com
  password: bigboss # can be encrypted
  domain: rpestano
  app: archetype
after_deploy:
  run: mvn test -Pft-tests -Pwildfly-managed -Premote-selenium

